### ISSUE TITLE
Kalenterilogiikan korjaus

### ISSUE THREAD

**Issue by kheldysh** [hys-helsinki/surma#54]
Pitää tarkistaa, katoaako aikavyöhyketieto matkalla, kun kalenteridataa haetaan ja/tai päivitetään. Vaikuttaako json<->string-muunnos?

**Comment by kheldysh** [comment]
Aiheesta jo Erikalta selvitystä ja hotfix-pulari: https://github.com/hys-helsinki/surma/pull/50

**Comment by xpyxpyx** [comment]
Tähän lisähuomio: kalenteri voi pidentyä pelaajalla, jos pelaaja käy Suomen aikavyöhykkeen ulkopuolella turnauksen aikana. Vastaavasti lyheneminen saattaa olla uhka.
